# Generated by Django 2.1.1 on 2018-11-04 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('altproduct', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='nutritation_image',
            new_name='nutrition_image',
        ),
    ]
