# Generated by Django 2.1.1 on 2018-11-11 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('altproduct', '0002_auto_20181104_1807'),
        ('altproduct', '0004_auto_20181103_1826'),
    ]

    operations = [
    ]
